### ISSUE TITLE
what is the solve and where did i go wrong please

### ISSUE THREAD

**Issue by Murphyfmg** [iceland2k14/rsz#12]
C:\Users\Murphy\Desktop\rsz-main>python getz_input.py -txid 82e5e1689ee396c8416b94c86aed9f4fe793a0fa2fa729df4a8312a287bc2d5e
Traceback (most recent call last):
  File "C:\Users\Murphy\Desktop\rsz-main\getz_input.py", line 14, in <module>
    parser.add_argument("", help = "txid of the transaction. Automatically fetch rawtx from given txid", action="store")
  File "C:\Users\MurphyE\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1401, in add_argument
    if not args or len(args) == 1 and args[0][0] not in chars:
IndexError: string index out of range

**Comment by Ak535Ak** [comment]
> 
![image](https://user-images.githubusercontent.com/79843719/198239744-b1385f88-8639-4627-a95b-84ced90f8062.png)
txid is correct, seems like you have problems with python on your side

**Comment by Murphyfmg** [comment]
please can you send me your own part of the code, i encounter so many error trying to run and i has solve some please

**Comment by Taimor-artist** [comment]
>>> python getz_input.py -txid 454c90738880a6635446805303c89871f0bb7b362d1ff9ff4e8646ff4e24ef49
  File "<stdin>", line 1
    python getz_input.py -txid 454c90738880a6635446805303c89871f0bb7b362d1ff9ff4e8646ff4e24ef49
                                 ^
SyntaxError: invalid decimal literal
>>>
KeyboardInterrupt
>>>

**Comment by Taimor-artist** [comment]
\Downloads\rsz-main\rsz-main>python getz_input.py -txid 454c90738880a6635446805303c89871f0bb7b362d1ff9ff4e8646ff4e24ef49

Starting Program...
UnSupported Tx Input. Presence of Witness Data
