### ISSUE TITLE
import secp256k1 as ice issue

### ISSUE THREAD

**Issue by dolcevita79** [iceland2k14/rsz#19]
/rsz# python3 rsz_solve.py
Traceback (most recent call last):
  File "rsz_solve.py", line 8, in <module>
    import secp256k1 as ice
  File "/root/rsz/secp256k1.py", line 32, in <module>
    ice = ctypes.CDLL(pathdll)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /root/rsz/ice_secp256k1.so)

please help why there is errors when try

**Comment by tm31420** [comment]
i have this exact error concerning this library. Would love to see it working for 18.04 ubuntu, i have 2.27 .
