### ISSUE TITLE
new idea from tm

### ISSUE THREAD

**Issue by tm31420** [iceland2k14/rsz#2]
i had an idea to make this rsz script accept a list of transaction ids in a separate file and parse them, and if there is an error or unparsable transaction, simply keep going to the next transaction id. just an idea. I love your rsz script, it rocks. this isn't an issue, just an idea.
thanks for the script,
tm

**Comment by Ango87** [comment]
@tm31420 Hello this script didn't work for me, I'm getting an error every time

**Comment by Ango87** [comment]
![Uploading Screenshot_20211214_205810_com.termux.jpg…]()

**Comment by Ango87** [comment]
![Uploading Screenshot_20211214_205810_com.termux.jpg…]()

**Comment by Ango87** [comment]
blink@localhost:/storage/emulated/0/Download/rsz-main$ ls
LICENSE  README.md  getz_input.py
blink@localhost:/storage/emulated/0/Download/rsz-main$ python getz_input.py
  File "getz_input.py", line 118
    print('='*70,f'\n[Input Index #: {i}]\n     R: {e[i][0]}\n     S: {e[i][1]}\n     Z: {e[i][2]}\nPubKey: {e[i][3]}')
                                                                                                                     ^
SyntaxError: invalid syntax
blink@localhost:/storage/emulated/0/Download/rsz-main$

**Comment by Ango87** [comment]
@tm31420 Thank you you are the best, brother please help me with this step too, every time I get a transaction for a bitcoin address I find a different r value I have tried with thousands of transactions, and I always have the same problem a different r value what should I do

**Comment by Ango87** [comment]
@tm31420

blink@localhost:/storage/emulated/0/Download/rsz-main$ python3 getz_input.py -txid ac6e619e7739cc247987d292929dc5f83c02489d20d90b243085f01d24dfbe39

Starting Program...
======================================================================
[Input Index #: 0]
     R: 2bcea2780dd225099eb01a126944dfacd0c1607ecb0980b6650e21c3367db8b4
     S: 37e1e361e58349041f4f9d208f90a9ab53d251527f5dc3c21f027f60fa7e16b6
     Z: c5845ba8e333d10bc223363113147fa826256fa1850cbd539443cd27b89cf1a2
PubKey: 023b7089f09e6e81032db8f892a8ec9851260c4366d24a6e8b3a2c8254aa4b335d
======================================================================
[Input Index #: 1]
     R: 07735d9e4bf613bb02e18a675da8f087f70a6e726852b02db8e4642e232bd1ab
     S: 22627429f8a74fdb4c3564cce94a843368ee3f802c06a0bbdfd0d2e5ba3a1fe9
     Z: 0cdc5a5117dca183226b405c344f87737a43701de4574c60e3737d71eca08556
PubKey: 023b7089f09e6e81032db8f892a8ec9851260c4366d24a6e8b3a2c8254aa4b335d
blink@localhost:/storage/emu

**Comment by Ango87** [comment]
blink@localhost:/storage/emulated/0/Download/rsz-main$ python3 getz_input.py -txid ac6e619e7739cc247987d292929dc5f83c02489d20d90b243085f01d24dfbe39

Starting Program...
======================================================================
[Input Index #: 0]
     R: 2bcea2780dd225099eb01a126944dfacd0c1607ecb0980b6650e21c3367db8b4
     S: 37e1e361e58349041f4f9d208f90a9ab53d251527f5dc3c21f027f60fa7e16b6
     Z: c5845ba8e333d10bc223363113147fa826256fa1850cbd539443cd27b89cf1a2
PubKey: 023b7089f09e6e81032db8f892a8ec9851260c4366d24a6e8b3a2c8254aa4b335d
======================================================================
[Input Index #: 1]
     R: 07735d9e4bf613bb02e18a675da8f087f70a6e726852b02db8e4642e232bd1ab
     S: 22627429f8a74fdb4c3564cce94a843368ee3f802c06a0bbdfd0d2e5ba3a1fe9
     Z: 0cdc5a5117dca183226b405c344f87737a43701de4574c60e3737d71eca08556
PubKey: 023b7089f09e6e81032db8f892a8ec9851260c4366d24a6e8b3a2c8254aa4b335d
blink@localhost:/storage/emu

**Comment by Ango87** [comment]
blink@localhost:/storage/emulated/0/Download/rsz-main$ python3 getz_input.py -txid ac6e619e7739cc247987d292929dc5f83c02489d20d90b243085f01d24dfbe39

Starting Program...
======================================================================
[Input Index #: 0]
     R: 2bcea2780dd225099eb01a126944dfacd0c1607ecb0980b6650e21c3367db8b4
     S: 37e1e361e58349041f4f9d208f90a9ab53d251527f5dc3c21f027f60fa7e16b6
     Z: c5845ba8e333d10bc223363113147fa826256fa1850cbd539443cd27b89cf1a2
PubKey: 023b7089f09e6e81032db8f892a8ec9851260c4366d24a6e8b3a2c8254aa4b335d
======================================================================
[Input Index #: 1]
     R: 07735d9e4bf613bb02e18a675da8f087f70a6e726852b02db8e4642e232bd1ab
     S: 22627429f8a74fdb4c3564cce94a843368ee3f802c06a0bbdfd0d2e5ba3a1fe9
     Z: 0cdc5a5117dca183226b405c344f87737a43701de4574c60e3737d71eca08556
PubKey: 023b7089f09e6e81032db8f892a8ec9851260c4366d24a6e8b3a2c8254aa4b335d
blink@localhost:/storage/emu

**Comment by tm31420** [comment]
different input, different r value, that is just the nature of the signature generation. I guess you are looking for duplicate r transactions, they are probably gonna be hard to find nowadays.

**Comment by Ango87** [comment]
@tm31420  Thank you brother, but I read a tip that I can't get the private key when I have a different value of r, is that correct, please teach me

**Comment by tm31420** [comment]
that is not public information. If the r values differ, it makes the calculation much more difficult for the average joe. If you don't know the linear relationship between the two signatures, it is guesswork or bruteforce work, imo. this may be of interest to you.

https://github.com/tm31420/ECDSA-SM2-Signing-Attack

**Comment by Ango87** [comment]
@tm31420  Do you have more detailed links, please?

**Comment by tm31420** [comment]
that link is a good one, what were you looking for exactly?

**Comment by Ango87** [comment]
@tm31420  I want to get one value for r, do you have a discord account so we can communicate better, I am a beginner in this field, I need someone to guide me

**Comment by tm31420** [comment]
my email is tm31420@gmail.com

**Comment by iceland2k14** [comment]
@tm31420 Thanks for the suggestion. I might consider it after returning from Holidays.

**Comment by timekswaste** [comment]
i need update please @tm31420 @iceland2k14 
how to scraper -txid in blockchain >> [https://www.blockchain.com/btc/unconfirmed-transactions ](url)
`python getz_input.py -txid <pass my scrape txid auto>` #mybadenglishwrite
and @iceland2k14 send your mail please

**Comment by tm31420** [comment]
@timekswaste, scrape the blockchain for what? Duplicate r values, or something else. Please explain.

**Comment by timekswaste** [comment]
every time i am go to blockchain get the transactions_id past  `python getz_input.py -txid 488d1e186b00ccb35aa97088362b2cc7b45deebbeaa5b1f63898fc2124af296e` 
so i need 
step 1: send request to blockchain fetch the current transactions_id and run the getz_input.py 
          print rsz many....
step 2: rsz to private key hexconvert
step 3: cheak for balance and found balance print (txid,privatekey,adderss)

**Comment by timekswaste** [comment]
-txid f9aa66876f79ed8870720e9019e769548f591d285cc2d16460c411c5da0912ca
**R**: 6fc545a0360d77a92e5f00ad13f947c48d3d61605b091f43d3b8c9aeca68a3ea
**S**: 472db6ab16c4b34442a123764e871bbf1c866810996a3117c7a4937ef0b92b52
**Z**: 49acf9eb7e34189460d96ef1d8ce0d6bd35e5ff659da757775244aeb887b398d
PubKey: 0242ae9c0bd6300b20b08709546b79a02ef3a297a7eee1299121e2f79eb646c5b

how to **rsz** to hex private key get in python

**Comment by Ango87** [comment]
@timekswaste Please can you tell me how you got one value for r ??

**Comment by timekswaste** [comment]
@Ango87
run this script https://github.com/FoxxD3V/btc-rsz/blob/master/RawTX_RSZ.py
output : show r s1s2 z1,z2
but i got error what my mistake

https://tbtc.bitaps.com/raw/transaction/ff948290ff332aed8f0e5d767118a02e8671578c6775a333bb4ee4d6ccfcf639
i am enter raw tx i got error https://github.com/FoxxD3V/btc-rsz/blob/master/RawTX_RSZ.py  
Traceback (most recent call last):
  File "RawTX_RSZ.py", line 13, in <module>
    s = keyUtils.derSigToHexSig(m[1][:-2])
  File "/home/runner/btc-rsz/keyUtils.py", line 32, in derSigToHexSig
    x, s = ecdsa.der.remove_integer(s)
  File "/usr/local/lib/python2.7/dist-packages/ecdsa/der.py", line 218, in remove_integer
    raise UnexpectedDER("Negative integers are not supported")
ecdsa.der.UnexpectedDER: Negative integers are not supported

**Comment by timekswaste** [comment]
guys iam watch this video https://www.youtube.com/watch?v=iLRbLKfRqwA only one rsz and public key use crack private key : its possible i dont know any idea find k,pk formula 
i just copy the code in this video 
#sagemath_method_crack 
p = 0x 
n = 0x

E = EllipticCurve(GF(p), [0, 7])
Fn = FiniteField(n)
xP = 0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798
yP = 0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8

r = 0x 
s = 0x
p = 0x #enter publickery 02 0r 03 /04 maybe

k = (()) #i dont know p,pk formula ,any idea guess
pk = ()
print(hex(pk))

video link not work i am backup this video click https://drive.google.com/file/d/10kqJp_Eiqf6s_7IU5T2WnthThF5b4srg/view?usp=sharing

**Comment by Hurd8x** [comment]
> guys iam watch this video https://www.youtube.com/watch?v=iLRbLKfRqwA only one rsz and public key use crack private key : its possible i dont know ,any idea find k,pk formula i just copy the code in this video #sagemath_method_crack p = 0x n = 0x
> 
> E = EllipticCurve(GF(p), [0, 7]) Fn = FiniteField(n) xP = 0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 yP = 0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8
> 
> r = 0x s = 0x p = 0x #enter publickery 02 0r 03 /04 maybe
> 
> k = (()) #i dont know p,pk formula ,any idea guess pk = () print(hex(pk))
> 
> video link not work i am backup this video click https://drive.google.com/file/d/10kqJp_Eiqf6s_7IU5T2WnthThF5b4srg/view?usp=sharing

This is a scam !!! Not send him yours money !!!

**Comment by Ango87** [comment]
@tm31420 I sent you a message on your email

This is my email address : crypotag@gmail.com

**Comment by amadhurkant** [comment]
@tm31420 Does all signatures have relation between random number?

**Comment by amadhurkant** [comment]
I have a btc address having 2559 btc, let's join forces to crack it. The R-Scanner.py is not working for 50+ txn.

**Comment by timekswaste** [comment]
send 2559btc adderss i will try

**Comment by amadhurkant** [comment]
1G47mSr3oANXMafVrR8UC4pzV7FEAzo3r9

**Comment by tm31420** [comment]
u have to change something for addresses with more than 10000 transactions.

**Comment by tm31420** [comment]
https://github.com/tm31420/Bitcoin-Tool-Linux-Version/blob/main/rscan10000.py

**Comment by tm31420** [comment]
1G47mSr3oANXMafVrR8UC4pzV7FEAzo3r9 is not weak, it has no dup r values that aren't are not r ==  r and s != s
the s values can't be the same, rscan10000.py accounts for that issue. It only outputs r==r where the s value is different.

try it with 1BFhrfTTZP3Nw4BNy4eX4KFLsn9ZeijcMm

**Comment by tm31420** [comment]
https://github.com/tm31420/Bitcoin-Tool-Linux-Version/blob/main/rscan.py

use this for addresses under 10000 transactions

**Comment by timekswaste** [comment]
Input-ScriptNR 30 :483045022100bd5d8d5f0961a17b8fdd566d73a3c3e7d70c2ff571dfaff74b10fd64bb55d57c022045f88de8da2b4f9a326b2489c49c57888c607a03a2e56655273e64428004b2fb0121024cdf5e77147d016a69d79cd2d706caa0cbd9e78c78368140eba601470389dfd3
what is input-ScriptNR,how to convert rsz  ,any python code

**Comment by amadhurkant** [comment]
For Z you need to provide the raw tx

**Comment by timekswaste** [comment]
@amadhurkant 
@tm31420 
i run rscan.py
i tested this adderss 1BFhrfTTZP3Nw4BNy4eX4KFLsn9ZeijcMm 
i find r-reuse output file : https://drive.google.com/file/d/1fsy2m6Enyg6Q91Wi2b30CzQuyj5g_edp/view?usp=sharing
what next, how get s1,s2,z1,z1 my output file or how to get r-reuse txid in my output file next i run this code getz_input.py -txid <r-reuse>
please teach me:

**Comment by timekswaste** [comment]
> > @amadhurkant @tm31420 i run rscan.py i tested this adderss 1BFhrfTTZP3Nw4BNy4eX4KFLsn9ZeijcMm i find r-reuse output file : https://drive.google.com/file/d/1fsy2m6Enyg6Q91Wi2b30CzQuyj5g_edp/view?usp=sharing what next, how get s1,s2,z1,z1 my output file or how to get r-reuse txid in my output file next i run this code getz_input.py -txid please teach me:
> 
> https://cryptoxploit.com/rsz-key/

update, rsacn.py print only Resued vulnerable-R txid
 https://github.com/tm31420/Bitcoin-Tool-Linux-Version/blob/main/rscan.py
this script print (Input-ScriptNR 1) ok #Input-ScriptNR 1:483045022011f195b0af4efcee63a1c04a7b4134392f2...etc
next print (Resued R-Value: ) ok #d47ce4c025c35ec440bc81d99834a624875161a26bf56ef7fdc0f5d52f843ad1
not print (Resued vulnerable txid) why #9ec4bc49e828d924af1d1029cacf709431abbde46d59554b62bc270e3b29c4b1
update please

reason, if rscan.py print vulnerable txid i get the txid and i easy to run getz_input.py -txid <> #output i get rsz easyly
example:
step1: rscan.py print this txid 9ec4bc49e828d924af1d1029cacf709431abbde46d59554b62bc270e3b29c4b1
step2: i run getz_input.py -txid <9ec4bc49e828d924af1d1029cacf709431abbde46d59554b62bc270e3b29c4b1>
easy to get rsz

#i killing english sorry

**Comment by kpot87** [comment]
> that is not public information. If the r values differ, it makes the calculation much more difficult for the average joe. If you don't know the linear relationship between the two signatures, it is guesswork or bruteforce work, imo. this may be of interest to you.
> 
> https://github.com/tm31420/ECDSA-SM2-Signing-Attack

Hi ! And relation between signatures is? Example: if one address  collect few small amount for send a bigger one to another address it can be relation between signatures?

**Comment by Ango87** [comment]
Who can help me I have two transactions for a bitcoin address that differ in the value of R, because of this problem I can't get the private key

from this wallet 1XCPdWb6kk7PGfvbdRbRuNh51aPc4vqC7

this is information tx 1 b152df9fc1087066cc12ec69c441f35559d794267209fd03f6d3f1d257b69549
raw tx : 010000000134930446c8a27fb457e65fa6f88a193843bf49a73043b997cfd005b9910173a7290000008a4730440220700d06f0d24f18e89acaf250b137b25066b4abea1f3cab58ba48b3dac7e3ede7022032236390aa15f60370236a9b88a5fbcc95aca95bbc7c32be2e781daf5ed1cd1601410433e05b29670f19cbc499f207f11abe1c69f77f00d5cbb9dbec5b5fe7527e2f41fa1e90f10a05e9c0a34d255988082e190c9ee7ea05f62297d4f76d9b61d7561bffffffff020000000000000000306a2ef24afce462d82863a3686fa4071c2d451a0e8c1056250110f8c08e8966f731b5d630d7b6a89c8ba88d3d388c3d4236150000000000001976a91405b5fca463964fc8af5ce743e1cfc1102601ecfc88ac00000000

THE R1 700d06f0d24f18e89acaf250b137b25066b4abea1f3cab58ba48b3dac7e3ede7 THE S1 32236390aa15f60370236a9b88a5fbcc95aca95bbc7c32be2e781daf5ed1cd16 THE Z1 b28f435e053ba045130a39562570bb7fcb7100d6501cb1571ee7bea979ea6377 THE PUBKEY : 0433e05b29670f19cbc499f207f11abe1c69f77f00d5cbb9dbec5b5fe7527e2f41fa1e90f10a05e9c0a34d255988082e190c9ee7ea05f62297d4f76d9b61d7561b')

tx 2 4fa22a2149dd320655425ad7a88b6f6aad87afe10bcf7117c2499b1d5af9529c

raw tx 2 : 010000000134930446c8a27fb457e65fa6f88a193843bf49a73043b997cfd005b9910173a7280000008b483045022100e13d5d80bab1b5734684334c652cdaa53bd63003b3fb5044e7cfabb78e3e6621022007f8c435382190f1b7d3f0318924e886360ff2b4a7a565fb36d2ed6b936b3e3e01410433e05b29670f19cbc499f207f11abe1c69f77f00d5cbb9dbec5b5fe7527e2f41fa1e90f10a05e9c0a34d255988082e190c9ee7ea05f62297d4f76d9b61d7561bffffffff020000000000000000306a2ef24afce462d82863a3686fa4071c2d451a0e8c105531133861c0ed81e886d159436a4e351103320143bbdae92a2836150000000000001976a91405b5fca463964fc8af5ce743e1cfc1102601ecfc88ac00000000

('THE R2 e13d5d80bab1b5734684334c652cdaa53bd63003b3fb5044e7cfabb78e3e6621') ('THE S2 07f8c435382190f1b7d3f0318924e886360ff2b4a7a565fb36d2ed6b936b3e3e') ('THE Z2 1e8faed746b6bcfbc42d8c2c75b58e1ba2f9059089be669bbb9365b84937e89c') ('THE PUBKey 0433e05b29670f19cbc499f207f11abe1c69f77f00d5cbb9dbec5b5fe7527e2f41fa1e90f10a05e9c0a34d255988082e190c9ee7ea05f62297d4f76d9b61d7561b')

**Comment by tm31420** [comment]
that address is not weak, imo. U may have a hard time finding the key to that one.

**Comment by kpot87** [comment]
hi!  @tm31420 how you are understand weak address or not?

**Comment by tm31420** [comment]
What u mean by weak.?? How the addresses are generated?? Explain weak referring to the "address"

**Comment by amadhurkant** [comment]
If the R are different than the private key can't be calculated.

**Comment by Hurd8x** [comment]
> If the R are different than the private key can't be calculated.

Try this ? https://qiita.com/YuasaJunki/items/5451d967ae02a1d66f53#crypto-love-letter

**Comment by amadhurkant** [comment]
I don't know the lang.

**Comment by Hurd8x** [comment]
> I don't know the lang.

You not know python, hmm inteesting.

Gl

**Comment by amadhurkant** [comment]
I dont know that language Chinese//Japaneese or any other.

>

**Comment by kpot87** [comment]
> > If the R are different than the private key can't be calculated.
> 
> Try this ? https://qiita.com/YuasaJunki/items/5451d967ae02a1d66f53#crypto-love-letter

А ты пробовал?

**Comment by tm31420** [comment]
https://qiita.com/YuasaJunki/items/5451d967ae02a1d66f53#crypto-love-letter
what about this, it works by modifying the generator point. It won't verify on the blockchain, will it kpot87?

**Comment by Hurd8x** [comment]
> https://qiita.com/YuasaJunki/items/5451d967ae02a1d66f53#crypto-love-letter what about this, it works by modifying the generator point. It won't verify on the blockchain, will it kpot87?

You need find privkey for generator poin for find privkey

**Comment by tm31420** [comment]
That's not hard, lol.

**Comment by Hurd8x** [comment]
> That's not hard, lol.

Depends of your random k. Target key = random k * fake basepoint privkey. Modification of random k is easy, bigger k depends smaler    fake basepoint privkey

**Comment by tm31420** [comment]
Doesn't the fake basepoint depend on the public key in question?

**Comment by tm31420** [comment]
Post an example here or send to my email, tm31420@gmail.com

**Comment by kpot87** [comment]
> > That's not hard, lol.
> 
> Depends of your random k. Target key = random k * fake basepoint privkey. Modification of random k is easy, bigger k depends smaler fake basepoint privkey

Что ты имеешь ввиду под basepoint?

**Comment by kpot87** [comment]
Hi all anybody try to make raw tx with already used R?

**Comment by amadhurkant** [comment]
> Hi all anybody try to make raw tx with already used R?
You can't.

**Comment by amadhurkant** [comment]
> Hi all anybody try to make raw tx with already used R?

No, you can't.

**Comment by Hurd8x** [comment]
> > > That's not hard, lol.
> > 
> > 
> > Depends of your random k. Target key = random k * fake basepoint privkey. Modification of random k is easy, bigger k depends smaler fake basepoint privkey
> 
> Что ты имеешь ввиду под basepoint?

В этом случае это модульная инверсия Толи к, умноженная на паблик, Толи модульная инверсия паблика умноженная на к. Даёт в результате публичный ключь от адреса.

**Comment by amadhurkant** [comment]
@tm31420 @iceland2k14 

Is there any code to calculate private key of I know nonce used to generate R.

**Comment by Hurd8x** [comment]
> @tm31420 @iceland2k14
> 
> Is there any code to calculate private key of I know nonce used to generate R.

Yes. https://github.com/malb/bdd-predicate/blob/master/sample_input.txt

**Comment by Ango87** [comment]
> @tm31420 @iceland2k14
> 
> Is there any code to calculate private key of I know nonce used to generate R.

@amadhurkant How can i get it

**Comment by tm31420** [comment]
K = ((Z + (X * R)) / S) % N

**Comment by tm31420** [comment]
X = (((S * K) - Z) / R) % N

**Comment by Ango87** [comment]
@tm31420  I have a value for r and s but of course the value of r is different. Can I use one of my different r values? to calculate it

**Comment by Hurd8x** [comment]
> @tm31420 I have a value for r and s but of course the value of r is different. Can I use one of my different r values? to calculate it

Only if you know last bit or first bit, or full nonce o sighnabtures

**Comment by Ango87** [comment]
@tm31420  @Hurd8x Is the value of N always the same?
N = 115792089237316195423570985008687907852837564279074904382605163141518161494337

**Comment by Hurd8x** [comment]
> @tm31420 @Hurd8x Is the value of N always the same? N = 115792089237316195423570985008687907852837564279074904382605163141518161494337

This is a order. Yes, alvays same

**Comment by Ango87** [comment]
> > @tm31420 I have a value for r and s but of course the value of r is different. Can I use one of my different r values? to calculate it
> 
> Only if you know last bit or first bit, or full nonce o sighnabtures

Sorry, I don't understand you very well, does that mean I can calculate it even with the different value of r

X = (((S * K) - Z) / R) % N

**Comment by Hurd8x** [comment]
> > > @tm31420 I have a value for r and s but of course the value of r is different. Can I use one of my different r values? to calculate it
> > 
> > 
> > Only if you know last bit or first bit, or full nonce o sighnabtures
> 
> Sorry, I don't understand you very well, does that mean I can calculate it even with the different value of r
> 
> X = (((S * K) - Z) / R) % N

You need know nonce. In this formula no has nonce.

**Comment by Ango87** [comment]
> 

How can I find nonce

**Comment by Ango87** [comment]
@Hurd8x please let me know how can I find nonce

**Comment by Hurd8x** [comment]
> > 
> 
> How can I find nonce

I dont know this is very hard task, all what, i lnow ethereum maybe has fixed nonce. Try reeds pdfs...

**Comment by Ango87** [comment]
> > > 
> > 
> > 
> > How can I find nonce
> 
> I dont know this is very hard task, all what, i lnow ethereum maybe has fixed nonce. Try reeds pdfs...

Anyway thank you for your support

**Comment by Ango87** [comment]
@Hurd8x what do you think of this video

https://youtu.be/3hbs9Yl6cqE

**Comment by Ankithuuuu** [comment]
What about this video guys, can you please help me find forge.py code ( with this forge.py we can easily find private key) [ this is forging technique for k ]
https://vimeo.com/694404329

**Comment by tm31420** [comment]
i have seen that code before...

**Comment by Hurd8x** [comment]
> 

Vide is a SCAM !!!! TAO140@PROTONMAIL, AND OTHER EMAILS OF THIS SCAMMER !!!

**Comment by Ankithuuuu** [comment]
> 

Where bro can i get that code please?

**Comment by Ankithuuuu** [comment]
> > 
> 
> Vide is a SCAM !!!! TAO140@PROTONMAIL, AND OTHER EMAILS OF THIS SCAMMER !!!

Then how to find private key from rsz values bro?

**Comment by Hurd8x** [comment]
> > > 
> > 
> > 
> > Vide is a SCAM !!!! TAO140@PROTONMAIL, AND OTHER EMAILS OF THIS SCAMMER !!!
> 
> Then how to find private key from rsz values bro?

No easy way !!!! You need rebuid rsz for convert them to rsz with MSB OR LSB !!! WITHOUT MSB OR LSB IT IS IMPOSIBLE !!! SCAMMWRS ARE VIDE NAKERS ONLY !!!

**Comment by Hurd8x** [comment]
I can provide you preious version of this scam for 200$, i was facked to 1000. Code work onlly with genersted data and not workbon real data.

**Comment by Hurd8x** [comment]
> > > 
> > 
> > 
> > Vide is a SCAM !!!! TAO140@PROTONMAIL, AND OTHER EMAILS OF THIS SCAMMER !!!
> 
> Then how to find private key from rsz values bro?

Try talk with she , she is professional maybe she answer you, post many queschion, ask his git dead or live etc ))) https://github.com/malb/bdd-predicate/issues/8

**Comment by Ankithuuuu** [comment]
![IMG_20220429_211905](https://user-images.githubusercontent.com/103119698/165979719-5883f352-6c49-45e8-b91e-80279ed25a5d.jpg)
Anyone help me to RSZ value in the same way as shown in the picture please help
