### ISSUE TITLE
tarting to prepare BSGS Table with 100000000 elements Traceback (most recent call last):   File "D:\Btc\rsz-main\rsz_rdiff_scan.py", line 221, in <module>     ice.bsgs_2nd_check_prepare(bP)     ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'secp256k1' has no attribute 'bsgs_2nd_check_prepare'

### ISSUE THREAD

**Issue by dry1515** [iceland2k14/rsz#21]
tarting to prepare BSGS Table with 100000000 elements
Traceback (most recent call last):
  File "D:\Btc\rsz-main\rsz_rdiff_scan.py", line 221, in <module>
    ice.bsgs_2nd_check_prepare(bP)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'secp256k1' has no attribute 'bsgs_2nd_check_prepare'

**Comment by iceland2k14** [comment]
just copy and paste file from https://github.com/iceland2k14/secp256k1 to D:\Btc\rsz-main\

**Comment by sari777** [comment]
> tarting to prepare BSGS Table with 100000000 elements Traceback (most recent call last): File "D:\Btc\rsz-main\rsz_rdiff_scan.py", line 221, in ice.bsgs_2nd_check_prepare(bP) ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'secp256k1' has no attribute 'bsgs_2nd_check_prepare'

any solution.?

**Comment by Mahuro** [comment]
everytime I run :
python3 rsz_rdiff_scan.py -a XXXXXXXXXXXXXXXXXXXXXX

Ithe program always stops at: 

0475a7b94e888c323cc40fba8d7b3aff86862aff6fdfa8f7cee949572961170bdb896ed7115fd3d5c4b89bc548282793cf0a479a9a627f5af4b22f7f85de5457ba
------------------------------------------------------------------------------------------------------------------------
Starting to prepare BSGS Table with 100000000 elements
======================================================================
------------------------------------------------------------------------------------------------------------------------
Program Finished ...
mahuro@WorkStation:~/rsz$ 

Always dies there and doesnt proceed from there....lol

**Comment by iceland2k14** [comment]
Program Finished means everything finished and Nothing is Found. That's it. END
