### ISSUE TITLE
Not Working!

### ISSUE THREAD

**Issue by battlenetcs** [iceland2k14/rsz#37]
git clone https://github.com/iceland2k14/secp256k1.git
:~/Desktop/Tests/ICE/secp256k1$ python3 secp256k1.py
seams to work without errors

git clone https://github.com/iceland2k14/rsz.git
:~/Desktop/Tests/ICE/rsz$ python3 getz_input.py -rawtx 0100000001e3a471fe05a55e961c10a0293c05a80bb2805b40be602bcdf6dbdfe1e49c5e20000000008a473044022045e5757bc8ed4882bf19e384e6e239b75c23611e9790d1169d2c6bbd6081f52e02203aefa1a97a038ea3827b5049835ff0ad93b4e0f1712e8b5e18a60086b0c018c00141047a51392bace353f4c3788c9c090ef4f635ec211159ec3b9f1bb7da7679517e126e98e0012bcb4d2b023c479afaaa1ad703ea1b24e1910e2cdad38744ba7aab8affffffff0100e1f505000000001976a91431f19a7d0379f56cb3be0761c21f1f0c9553a47f88ac00000000

Starting Program...
Traceback (most recent call last):
  File "getz_input.py", line 117, in <module>
    e = getSignableTxn(m)
  File "getz_input.py", line 95, in getSignableTxn
    e += '1976a914' + HASH160(inp_list[one][4]) + '88ac'
  File "getz_input.py", line 106, in HASH160
    P = ice.pub2upub(pubk_hex)
AttributeError: module 'secp256k1' has no attribute 'pub2upub'

Seams it does not find attribute 'pub2upub'

**Comment by iceland2k14** [comment]
files in secp256k1 should be inside the folder rsz. Both in different folder so the script is not able to find those files.

**Comment by battlenetcs** [comment]
done that but!

~/Desktop/Tests/ICE/rsz$ python3 getz_input.py -rawtx 0100000001e3a471fe05a55e961c10a0293c05a80bb2805b40be602bcdf6dbdfe1e49c5e20000000008a473044022045e5757bc8ed4882bf19e384e6e239b75c23611e9790d1169d2c6bbd6081f52e02203aefa1a97a038ea3827b5049835ff0ad93b4e0f1712e8b5e18a60086b0c018c00141047a51392bace353f4c3788c9c090ef4f635ec211159ec3b9f1bb7da7679517e126e98e0012bcb4d2b023c479afaaa1ad703ea1b24e1910e2cdad38744ba7aab8affffffff0100e1f505000000001976a91431f19a7d0379f56cb3be0761c21f1f0c9553a47f88ac00000000

Starting Program...
Traceback (most recent call last):
  File "getz_input.py", line 121, in <module>
    e = getSignableTxn(m)
  File "getz_input.py", line 95, in getSignableTxn
    e += '1976a914' + HASH160(inp_list[one][4]) + '88ac'
  File "getz_input.py", line 110, in HASH160
    pubkey = ice.ec_pubkey_parse_uncompressed(pubk)
AttributeError: module 'secp256k1' has no attribute 'ec_pubkey_parse_uncompressed'

**Comment by battlenetcs** [comment]
I would suggest to add detailed instructions in running the scripts.
Personally i tried different methods, non seam to work
In the mean time i created a small py script to extract the RSZ, your tool has more options and would still like to use it....

**Comment by aesthetic28** [comment]
C:\Users\Aditya Kurnia R\rsz>python getz_input.py -txid a79890xxxxxxxxxxxxxxxxxxxxxxxxxx


Starting Program...
UnSupported Tx Input. Presence of Witness Data

**Comment by Mahuro** [comment]
You can only run this on legacy addresses that begin with 1.

**Comment by maxwellgolden** [comment]
hello bro i'm facing the same issue.

please how did you resolve it



Starting Program...
Traceback (most recent call last):
File "getz_input.py", line 117, in
e = getSignableTxn(m)
File "getz_input.py", line 95, in getSignableTxn
e += '1976a914' + HASH160(inp_list[one][4]) + '88ac'
File "getz_input.py", line 106, in HASH160
P = ice.pub2upub(pubk_hex)
AttributeError: module 'secp256k1' has no attribute 'pub2upub'

Seams it does not find attribute 'pub2upub'

**Comment by iceland2k14** [comment]
Copy your files from ~/Desktop/Tests/ICE/secp256k1/* into the folder ~/Desktop/Tests/ICE/rsz/

And then run
