### ISSUE TITLE
Different r value 

### ISSUE THREAD

**Issue by Ango87** [iceland2k14/rsz#4]
@iceland2k14 Hello brother, every time I extract values from any bitcoin transaction, I get a different value of r, and I don't get the private key of the wallet I want because of a different value of r, please guide me to a way to get one value of r in any bitcoin transaction, and if you You can't give me this information in a year, please give me any way to contact you

**Comment by Hurd8x** [comment]
Yes, r value are different. For use atrack against different value need same scrypt. Ex, https://asecuritysite.com/ecc/ecd but ofcause you need replase in code r,s,z

**Comment by Ango87** [comment]
@Hurd8x Thank you very much for your help. Please, brother, tell me what to do step by step. I am a beginner. I do not know how to change the code. Can we communicate on WhatsApp or any method of communication you choose, and if you can here, please do this

**Comment by Ango87** [comment]
@Hurd8x  How can I change the code from base 16 to base58, also I have a Bitcoin address and I want to get its private key, how can I add this address data to the code

**Comment by Hurd8x** [comment]
> @Hurd8x How can I change the code from base 16 to base58, also I have a Bitcoin address and I want to get its private key, how can I add this address data to the code

For changing code I use freelancers. Base 16 to base 58, I not seen this in the code. Prepare fo freelancer r,s,z(hashed message) and ask him modofy code

**Comment by Ango87** [comment]
@Hurd8x  Hello, how can I contact you? If you have a Discord account or any other means of communication, please let me know

**Comment by Taimor-artist** [comment]
when i try to find value of any transaction in python RawTX_RSZ.py I got  error

**Comment by samibannour0** [comment]
what mean this error   python rsz_solve.py
Traceback (most recent call last):
  File "/root/rsz/rsz_solve.py", line 10, in <module>
    G = ice.scalar_multiplication(1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'secp256k1' has no attribute 'scalar_multiplication'

**Comment by samibannour0** [comment]
when i run this file "rsz_solve.py"
I see this message 
"Traceback (most recent call last):
  File "/root/rsz/rsz_solve.py", line 10, in <module>
    G = ice.scalar_multiplication(1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'secp256k1' has no attribute 'scalar_multiplication'"

**Comment by Mahuro** [comment]
> Yes, r value are different. For use atrack against different value need same scrypt. Ex, https://asecuritysite.com/ecc/ecd but ofcause you need replase in code r,s,z

Hello @Hurd8x 
so in that page: https://asecuritysite.com/ecc/ecd ... what values you enter as parameters?

Thank you.
