### ISSUE TITLE
What happenend to iceland2K14 ???

### ISSUE THREAD

**Issue by Mahuro** [iceland2k14/rsz#45]
I mean the man ( or woman) totally disappeared....

was he/she taken away by the greys? the Illuminati got him/her?  has he ben taken out by a CIA sniper?

**Comment by coolmib** [comment]
He / She just update the Secp256k1 3 days ago

**Comment by Mahuro** [comment]
Great. I wish he/she answered some of the questions....

**Comment by maxwellgolden** [comment]
> He / She just update the Secp256k1 3 days ago

i'm having this issue . any idea on how to solve them?



Starting Program...
Traceback (most recent call last):
File "getz_input.py", line 117, in
e = getSignableTxn(m)
File "getz_input.py", line 95, in getSignableTxn
e += '1976a914' + HASH160(inp_list[one][4]) + '88ac'
File "getz_input.py", line 106, in HASH160
P = ice.pub2upub(pubk_hex)
AttributeError: module 'secp256k1' has no attribute 'pub2upub'

Seams it does not find attribute 'pub2upub'

**Comment by coolmib** [comment]
> > He / She just update the Secp256k1 3 days ago
> 
> i'm having this issue . any idea on how to solve them?
> 
> Starting Program... Traceback (most recent call last): File "getz_input.py", line 117, in e = getSignableTxn(m) File "getz_input.py", line 95, in getSignableTxn e += '1976a914' + HASH160(inp_list[one][4]) + '88ac' File "getz_input.py", line 106, in HASH160 P = ice.pub2upub(pubk_hex) AttributeError: module 'secp256k1' has no attribute 'pub2upub'
> 
> Seams it does not find attribute 'pub2upub'

try to using the latest one both rsz and secp256k1
